services:
  vanilla:
    build:
      context: .
    image: vanilla
    container_name: vanilla
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
    restart: always
